basePath: /
definitions:
  model.Json:
    properties:
      code:
        type: integer
      data: {}
      flag:
        type: boolean
      msg:
        type: string
    type: object
host: localhost:8080
info:
  contact: {}
  title: 前后端分离商城
  version: "1.0"
paths:
  /user/info:
    get:
      consumes:
      - application/json
      description: 解码token获取信息
      parameters:
      - description: token串
        in: query
        name: string
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.Json'
      summary: 解码token获取信息
      tags:
      - 用户相关接口
  /user/login:
    post:
      consumes:
      - application/json
      description: 传入用户名和密码进行登录
      parameters:
      - in: formData
        name: email
        type: string
      - in: formData
        name: id
        type: integer
      - in: formData
        name: password
        type: string
      - in: formData
        name: phone
        type: string
      - in: formData
        name: username
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.Json'
      summary: 用户登录接口
      tags:
      - 用户相关接口
  /user/register:
    post:
      consumes:
      - application/json
      description: 传入用户信息进行注册
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.Json'
      summary: 用户注册接口
      tags:
      - 用户相关接口
swagger: "2.0"
